repos:
  - repo: local
    hooks:
      - id: local-black
        name: Black
        entry: uv run black
        language: system
        types: [python]

      - id: local-ruff
        name: Ruff
        entry: uv run ruff check --fix
        language: system
        types: [python]

      - id: local-mypy
        name: Mypy
        entry: uv run mypy
        language: system
        types: [python]
        stages: [manual]
